/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SolutionType { 
    id?: number;
    name?: string;
    solutionTypeStatus?: SolutionType.SolutionTypeStatusEnum;
}
export namespace SolutionType {
    export const SolutionTypeStatusEnum = {
        Active: 'ACTIVE',
        Inactive: 'INACTIVE'
    } as const;
    export type SolutionTypeStatusEnum = typeof SolutionTypeStatusEnum[keyof typeof SolutionTypeStatusEnum];
}


