/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TicketElement { 
    id?: number;
    name?: string;
    ticketElementStatus?: TicketElement.TicketElementStatusEnum;
}
export namespace TicketElement {
    export const TicketElementStatusEnum = {
        Active: 'ACTIVE',
        Inactive: 'INACTIVE'
    } as const;
    export type TicketElementStatusEnum = typeof TicketElementStatusEnum[keyof typeof TicketElementStatusEnum];
}


