/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplaintTicket } from './complaintTicket';
import { TicketingUser } from './ticketingUser';


export interface Comment { 
    id?: number;
    commentText?: string;
    commenter?: TicketingUser;
    ticket?: ComplaintTicket;
    commentedWhen?: string;
}

