/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { TicketElement } from './ticketElement';
import { SolutionType } from './solutionType';
import { Client } from './client';
import { TicketingUser } from './ticketingUser';


export interface ComplaintTicket { 
    ticketId?: number;
    client?: Client;
    ticketType?: ComplaintTicket.TicketTypeEnum;
    ticketElement?: TicketElement;
    createdWhen?: string;
    createdBy?: TicketingUser;
    description?: string;
    ticketStatus?: ComplaintTicket.TicketStatusEnum;
    slaHours?: number;
    assignedTo?: TicketingUser;
    assignedWhen?: string;
    solutionType?: SolutionType;
    solutionDescription?: string;
    closedBy?: TicketingUser;
    closedWhen?: string;
    cancelledBy?: TicketingUser;
    cancelledWhen?: string;
    comments?: Array<Comment>;
}
export namespace ComplaintTicket {
    export const TicketTypeEnum = {
        Complaint: 'COMPLAINT',
        Request: 'REQUEST',
        Incident: 'INCIDENT'
    } as const;
    export type TicketTypeEnum = typeof TicketTypeEnum[keyof typeof TicketTypeEnum];
    export const TicketStatusEnum = {
        New: 'NEW',
        Assigned: 'ASSIGNED',
        InProgress: 'IN_PROGRESS',
        Resolved: 'RESOLVED',
        Closed: 'CLOSED',
        Cancelled: 'CANCELLED'
    } as const;
    export type TicketStatusEnum = typeof TicketStatusEnum[keyof typeof TicketStatusEnum];
}


