/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TicketingUserDto { 
    id?: string;
    username?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    userRole?: TicketingUserDto.UserRoleEnum;
    createdAt?: string;
}
export namespace TicketingUserDto {
    export const UserRoleEnum = {
        Admin: 'ADMIN',
        User: 'USER',
        Supervisor: 'SUPERVISOR'
    } as const;
    export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];
}


