/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { TicketElement } from './ticketElement';
import { SolutionType } from './solutionType';
import { CommentDto } from './commentDto';


export interface TicketDto {
    ticketId?: number;
    ticketType?: TicketDto.TicketTypeEnum;
    ticketElement?: TicketElement;
    createdWhen?: string;
    createdBy?: User;
    description?: string;
    ticketStatus?: TicketDto.TicketStatusEnum;
    slaHours?: number;
    assignedTo?: User;
    assignedWhen?: string;
    solutionType?: SolutionType;
    solutionDescription?: string;
    closedBy?: User;
    closedWhen?: string;
    cancelledBy?: User;
    cancelledWhen?: string;
    comments?: Array<CommentDto>;
}
export namespace TicketDto {
    export const TicketTypeEnum = {
        Complaint: 'COMPLAINT',
        Request: 'REQUEST',
        Incident: 'INCIDENT'
    } as const;
    export type TicketTypeEnum = typeof TicketTypeEnum[keyof typeof TicketTypeEnum];
    export const TicketStatusEnum = {
        New: 'NEW',
        Assigned: 'ASSIGNED',
        InProgress: 'IN_PROGRESS',
        Resolved: 'RESOLVED',
        Closed: 'CLOSED',
        Cancelled: 'CANCELLED'
    } as const;
    export type TicketStatusEnum = typeof TicketStatusEnum[keyof typeof TicketStatusEnum];
}


